### ISSUE TITLE
Networks Bug Glitch

### ISSUE THREAD

**Issue by SrMonsterYT** [Sefiraat/Networks#114]
Server version and addons: https://prnt.sc/N8KNauwskR65

Bug video: https://youtu.be/kIjK9ZbDy9I

the video shows the bug how to farm concrete infinitely

**Comment by Sefiraat** [comment]
This can be an issue when placing and breaking Slimefun blocks in a manner this fast. I wouldn't exactly call it infinite gaming as you are effectively trading a storage unit for a terracotta, very bad trade imo 😀 
This is a known issue within slimefun and helpfully it will be fixed with the blockstorage rewrite!
