### ISSUE TITLE
Quantum storage will turn back into normal terracotta

### ISSUE THREAD

**Issue by DeathsValentine** [Sefiraat/Networks#176]
Sometimes the 2m quantum storage will turn back into normal brown terracotta randomly, without having been touched. I can't seem to figure out what triggers it or when it happens. So far I've only had trouble with 2m but I don't have as many 16m placed down. The ones that are turning into normal terracotta are ones that are holding slimefun items such as dusts, ingots, and synthetic gems.

Server version: Paper(447) 1.20.4-R0.1-SNAPSHOT+

![image_2024-05-14_201630882](https://github.com/Sefiraat/Networks/assets/39684769/1ece86e1-2d45-46f7-89ad-24853cc88e0c)

**Comment by lukariosmen** [comment]
Same problem on my server.

**Comment by JustAHuman-xD** [comment]
This isn't an issue with networks itself, it's a problem with Slimefun, specifically issues with block storage

**Comment by Sefiraat** [comment]
As above, there isn't much I can directly do here. It does happen more with Networks than other addons, but that is largely due to Networks often having you place thousands of blocks over just the one. Please note I am aware of this and if it ever comes to the point that I can resolve this directly, know I will :D
