### ISSUE TITLE
network components placed close to server restart revert to vanilla blocks

### ISSUE THREAD

**Issue by Boomer-1** [Sefiraat/Networks#45]
the last 3 restarts on royale, items I placed within a couple minutes of the restart turn to vanilla blocks after the restart.

it's happened on the last 2 scheduled restarts, and an emergency reboot after a crash

**Comment by mio9** [comment]
From the description provided, it looks more like the issue on how slimefun save data instead of the issue of this particular addon. Normally, slimefun would run a 10 minute scheduler on saving data (and therefore, the blocks), and also save again on shutdown. If it happens that the restart was not done properly, i.e. process killed or crashed, slimefun would not save the changes in the queue and therefore downgrading your slimefun block back to vanilla.

**Comment by Sefiraat** [comment]
I'm going to close this for now as it's not something I can really track nor maintain, but I will keep an eye open for more on this
