### ISSUE TITLE
[Suggestion] "Smart" Pushers

### ISSUE THREAD

**Issue by Raizune** [Sefiraat/Networks#97]
Similar to how cargo nodes work with "Smart Filter", this pusher node i am suggesting will only push a stack into a machine at a time and refrain from adding another stack in any other slot within said machine.

Recipe Suggestion: Pusher Network Node + Ai Core + 4 Optic Cables

This came up as a logistical issue for me when dealing with machines like Vaporizers (Bucket+Obsidian=Lava Bucket) Where as they would frequently overfill on obsidian.

**Comment by Sefiraat** [comment]
In a rare move for me, I will not implement this.

The issue here is that to properly implement this, the code will need to do an item comparison (potentially) on every single item within a BlockMenu/Inventory which is very taxing. In simple 2 slots menus, this would likely be fine but for all possible applications I'd be leaving a server open to very taxing operations, which is against the grain of Networks.
